### ISSUE TITLE
SyncPubsub::handleInterest - why sendSyncInterest()

### ISSUE THREAD

**Issue by yoursunny** [pollere/DNMP#1]
In *syncps* implementation, when `SyncPubsub::handleInterest` function decides to reply to a sync Interest because at least one of the locally generated publication is not in the peer's IBF, in addition to replying to the sync Interest with a sync Data, it also sends a new sync Interest.

https://github.com/pollere/DNMP/blob/5422a3c5347fd2882c0a1b12407c346c0c43b3a9/syncps/syncps.hpp#L437-L439

This operation seems unnecessary, because the local IBF has not changed, and the previous Interest carrying the local IBF is still pending in the network.
Is there something I overlooked?

**Comment by van-pollere** [comment]
Thanks for the bug report! This should be fixed in v0.3.0.
