### ISSUE TITLE
C++17 is incompatible with ndn-cxx

### ISSUE THREAD

**Issue by yoursunny** [pollere/DNMP#3]
DNMP codebase requires C++17 compilation:
https://github.com/pollere/DNMP/blob/37ee44a095720e815de54d8784be40022a62f777/Makefile#L2-L3
ndn-cxx is only compatible with C++14. Moreover, @Pesa has informed me that ndn-cxx headers can only be used in downstream projects compiled in C++14 mode, and you cannot use ndn-cxx headers in a translation unit compiled in C++17 mode.

Currently, the following error appears when compiling this codebase with ndn-cxx (either 'master' branch or 0.6.6 release:
```
$ make CXX=g++-9
g++-9 -g -O2 -I. -Wall -std=c++17 -pthread -DBOOST_LOG_DYN_LINK -I/usr/local/include -o genericCLI generic-client.cpp -L/usr/local/lib -pthread -lndn-cxx -lboost_system -lboost_program_options -lboost_chrono -lboost_date_time -lboost_filesystem -lboost_thread -lboost_log -lcrypto -lsqlite3 -lrt -lpthread -lboost_iostreams
/tmp/ccDNYZZi.o: In function `CRshim::buildCmd(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
/home/user/code/DNMP/CRshim.hpp:144: undefined reference to `ndn::Name::appendTimestamp(std::optional<boost::chrono::time_point<ndn::time::system_clock, boost::chrono::duration<long, boost::ratio<1l, 1000000000l> > > >)'
collect2: error: ld returned 1 exit status
Makefile:24: recipe for target 'genericCLI' failed
make: *** [genericCLI] Error 1
```

To fix this bug, DNMP codebase needs to either switch to C++14, or separate C++14 and C++17 into different translation units and ensure ndn-cxx headers are compiled in C++14 mode only.

**Comment by kmnichols** [comment]
The string problem is because the gnu compiler handles strings in a non-standard way. There may be a way to override this with an environment variable if you want to look into it. We are using a standards-compliant cross-platform compiler, clang, on MacOS and Linux without problems. There are NDN (cxx and nfd) build issues because of its non-compliance with the c++ <version> standard and a patch for this was supplied in the github.com/pollere/NDNpatches repo, see its README.

**Comment by yoursunny** [comment]
> There are NDN (cxx and nfd) build issues because of its non-compliance with the c++ standard and a patch for this was supplied in the github.com/pollere/NDNpatches repo

The `VERSION` file has been renamed to `VERSION.info` recently, when @cawka discovered the same problem.
https://github.com/named-data/ndn-cxx/commit/3de8aac22d6eba503e4e0d647ef73b160ece769f

I'll try clang later.

**Comment by yoursunny** [comment]
I'm able to compile DNMP on Ubuntu 18.04 with the following steps.

```shell
sudo apt install g++-8

CODEROOT=$HOME/code
mkdir -p $CODEROOT

cd $CODEROOT
git clone https://github.com/pollere/NDNpatches.git
git clone https://github.com/pollere/DNMP.git
git clone https://github.com/named-data/ndn-cxx.git
git clone --recursive https://github.com/named-data/NFD.git

cd $CODEROOT/ndn-cxx
git checkout ndn-cxx-0.7.0
git apply < $CODEROOT/NDNpatches/build-system.patch
./waf configure
./waf
sudo ./waf install
sudo ldconfig

cd $CODEROOT/NFD
git checkout NFD-0.7.0
git apply < $CODEROOT/NDNpatches/build-system.patch
./waf configure
./waf
sudo ./waf install

cd $CODEROOT/DNMP
CXX=g++-8 make
```

It does not work with `g++-7` (default compiler on Ubuntu 18.04). The error is:

```plain
generic-client.cpp:29:10: fatal error: charconv: No such file or directory
 #include <charconv>
          ^~~~~~~~~~
compilation terminated.
```

For `clang-8`, it has the same error if `g++-8` is not installed. It compiles successfully after installing `g++-8` that pulls in `libstdc++-8-dev` package.

**Comment by yoursunny** [comment]
I only applied `build-system.patch` due to https://github.com/pollere/NDNpatches/issues/1

**Comment by yoursunny** [comment]
This is no longer relevant because ndn-cxx now supports C++17.
